server:
  port: 8686

# 远程数据库数据源
#spring:
#  datasource:
#    username: root
#    password: wsfyz
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://123.56.156.212:3306/hncj_course_assistant?serverTimezone=UTC&useSSL=true

# 本地数据库数据源
spring:
  datasource:
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/hncj_course_assistant?serverTimezone=UTC&useSSL=true

# 整合mybatis
mybatis:
  type-aliases-package: cn.hncj.assistant.entity
  mapper-locations: classpath:mybatis/mappers/*.xml
