server:
  port: 8686

# 数据源
spring:
  datasource:
    username: root
    password: wsfyz
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://123.56.156.212:3306/hncj_course_assistant?serverTimezone=UTC&useSSL=true

# 整合mybatis
mybatis:
  type-aliases-package: cn.hncj.assistant.pojo
  mapper-locations: classpath:mybatis/mappers/*.xml
